language: minimal
arch:
 - amd64
 - arm64
env:
  global:
  - DOCKER_NAME_TAG=ubuntu:19.10  # Use docker only to pin to a specific version of an OS
install:
    - travis_retry docker pull "$DOCKER_NAME_TAG"
    - DOCKER_ID=$(docker run -idt --mount type=bind,src=$TRAVIS_BUILD_DIR,dst=$TRAVIS_BUILD_DIR $DOCKER_NAME_TAG)
    - DOCKER_EXEC () { docker exec $DOCKER_ID bash -c "cd $PWD && $*"; }
    - DOCKER_EXEC ./bin/install.sh
script:
    - travis_wait 40 DOCKER_EXEC \~/.local/bin/bitcoinperf examples/travis.yml
